language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAYIVQKIF2TYQ3XFNY
  secret_access_key:
    secure: dUN7OHSl6C+utD06nuxnThpgXj3503tdtImWildlVc+luOcCjb+/4Jbz3f0Jr3d7d3NAFc2jWGQo/rNTR3EuPoyO5LGKplWZuZdmBThWmOqZmHPjQReozByCX4nCWe3iWp29yBAeh1m/rTa7sdAGU2ITEM39EEFxohsFZPyGlTmZzPBhzKGQJ+g72Ff/KfT8X5r9+l7zzOHtvZ44EjYen5ByU+WA4cKjUTzXftIsHqKEZBrA6BrTOULa2Lgo2z18NRBXzmkQJNujBvFeZnQsq2ZByPQABkMQs2UuiPwy4/vujHew/FkkLNsSpX8Uv/z4IO3DVrBDA1EXrwE1+Yf9dn3yXxwBghFkjloQiQInFjgIVm2EMKI6UdLDGYxaojROY6x9EzvNy2a6VG42unekvWRtrzQSjoPB4+6M1AfRLbHwS8MqGznsh4cgYmU6Y80aDz2wbxbDNb4/L1TAyaDZ2JrivgE5eIzbYXPXCXXWYjgv2sbDLQfEJbbR3HTI4VRZxTo5bmzjXb2MIXGQgVG0BvlNMh68QDq5x2Pxzoq5Mps/IwRMlsZ0QzkPW6iV9JndT0fHP3m5aHZrMu99Rggsn+K6Il+pqEz9Htx68t3q8t6TMu1JkGCNJcZzB/mnKCLdnOlQEE+VGZHvqvBs01L5MTSibilnvwkxbQIq03SUPFQ=
  bucket: wangbox
  region: ap-east-1
  acl: public_owner_full_control
  on:
    repo: wangtoday/travis-demo